name: CI

on:
  push:
    branches:
      - main
      - release/*
      - feat/*
  pull_request:
    branches:
      - main
      - release/*
      - feat/*
  workflow_dispatch:

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Check Formatting
        run: uv run ruff format --check .

      - name: Lint Code
        run: uv run ruff check .

      - name: Type Check
        run: uv run basedpyright src

      - name: Build Check
        run: uv build
